"""remove type column to Quiz  model

Revision ID: 32582d5abb40
Revises: 451b44010b2c
Create Date: 2024-09-11 17:07:47.556263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32582d5abb40'
down_revision = '451b44010b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
